services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hastelecom
      POSTGRES_USER: hastelecom
      POSTGRES_PASSWORD: hastelecom_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://hastelecom:hastelecom_pass@postgres:5432/hastelecom
      JWT_SECRET: super-secret-change-me
      CRM_ORIGIN: http://has-telecom.local
    depends_on:
      - postgres

  crm:
    build:
      context: .
      dockerfile: apps/crm/Dockerfile

  landing:
    build:
      context: .
      dockerfile: apps/landing/Dockerfile

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    depends_on:
      - api
      - crm
      - landing
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
